//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pcm.WebUi.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pcm.WebUi.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        internal static string trainingName {
            get {
                return ResourceManager.GetString("trainingName", resourceCulture);
            }
        }
        
        internal static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        internal static string emailNotValid {
            get {
                return ResourceManager.GetString("emailNotValid", resourceCulture);
            }
        }
        
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static string saving {
            get {
                return ResourceManager.GetString("saving", resourceCulture);
            }
        }
        
        internal static string personnelNumber {
            get {
                return ResourceManager.GetString("personnelNumber", resourceCulture);
            }
        }
        
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        internal static string orderNumber {
            get {
                return ResourceManager.GetString("orderNumber", resourceCulture);
            }
        }
        
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        internal static string persons {
            get {
                return ResourceManager.GetString("persons", resourceCulture);
            }
        }
        
        internal static string articles {
            get {
                return ResourceManager.GetString("articles", resourceCulture);
            }
        }
        
        internal static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string createNewTQuestionWithName {
            get {
                return ResourceManager.GetString("createNewTQuestionWithName", resourceCulture);
            }
        }
        
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        internal static string articleType {
            get {
                return ResourceManager.GetString("articleType", resourceCulture);
            }
        }
        
        internal static string createNewTQuestion {
            get {
                return ResourceManager.GetString("createNewTQuestion", resourceCulture);
            }
        }
        
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        internal static string apprenticeships {
            get {
                return ResourceManager.GetString("apprenticeships", resourceCulture);
            }
        }
        
        internal static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }
        
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        internal static string belongingTrainees {
            get {
                return ResourceManager.GetString("belongingTrainees", resourceCulture);
            }
        }
        
        internal static string sortBy {
            get {
                return ResourceManager.GetString("sortBy", resourceCulture);
            }
        }
        
        internal static string trainingType {
            get {
                return ResourceManager.GetString("trainingType", resourceCulture);
            }
        }
        
        internal static string training {
            get {
                return ResourceManager.GetString("training", resourceCulture);
            }
        }
        
        internal static string trainees {
            get {
                return ResourceManager.GetString("trainees", resourceCulture);
            }
        }
        
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        internal static string trainings {
            get {
                return ResourceManager.GetString("trainings", resourceCulture);
            }
        }
        
        internal static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        internal static string defaultLoadout {
            get {
                return ResourceManager.GetString("defaultLoadout", resourceCulture);
            }
        }
        
        internal static string itemCategory {
            get {
                return ResourceManager.GetString("itemCategory", resourceCulture);
            }
        }
        
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        internal static string traineeCount {
            get {
                return ResourceManager.GetString("traineeCount", resourceCulture);
            }
        }
        
        internal static string yearCount {
            get {
                return ResourceManager.GetString("yearCount", resourceCulture);
            }
        }
        
        internal static string trainingDetails {
            get {
                return ResourceManager.GetString("trainingDetails", resourceCulture);
            }
        }
        
        internal static string createNewT {
            get {
                return ResourceManager.GetString("createNewT", resourceCulture);
            }
        }
        
        internal static string yearStarted {
            get {
                return ResourceManager.GetString("yearStarted", resourceCulture);
            }
        }
        
        internal static string tWithNameSuccessfullyCreated {
            get {
                return ResourceManager.GetString("tWithNameSuccessfullyCreated", resourceCulture);
            }
        }
        
        internal static string tWithNameNotSuccessfullyCreated {
            get {
                return ResourceManager.GetString("tWithNameNotSuccessfullyCreated", resourceCulture);
            }
        }
        
        internal static string editT {
            get {
                return ResourceManager.GetString("editT", resourceCulture);
            }
        }
        
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        internal static string reallyWantDeleteCannotBeUndone {
            get {
                return ResourceManager.GetString("reallyWantDeleteCannotBeUndone", resourceCulture);
            }
        }
        
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        internal static string tWithNameNotSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("tWithNameNotSuccessfullyUpdated", resourceCulture);
            }
        }
        
        internal static string tWithNameSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("tWithNameSuccessfullyUpdated", resourceCulture);
            }
        }
        
        internal static string tWithNameSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("tWithNameSuccessfullyDeleted", resourceCulture);
            }
        }
        
        internal static string tWithNameNotSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("tWithNameNotSuccessfullyDeleted", resourceCulture);
            }
        }
        
        internal static string startingYear {
            get {
                return ResourceManager.GetString("startingYear", resourceCulture);
            }
        }
        
        internal static string TCouldNotLoadedSuccessfully {
            get {
                return ResourceManager.GetString("TCouldNotLoadedSuccessfully", resourceCulture);
            }
        }
        
        internal static string itemCategories {
            get {
                return ResourceManager.GetString("itemCategories", resourceCulture);
            }
        }
        
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
    }
}
