//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pcm.WebUi.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pcm.WebUi.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string apprenticeship {
            get {
                return ResourceManager.GetString("apprenticeship", resourceCulture);
            }
        }
        
        internal static string emailAddress {
            get {
                return ResourceManager.GetString("emailAddress", resourceCulture);
            }
        }
        
        internal static string emailNotValid {
            get {
                return ResourceManager.GetString("emailNotValid", resourceCulture);
            }
        }
        
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static string saving {
            get {
                return ResourceManager.GetString("saving", resourceCulture);
            }
        }
        
        internal static string personnelNumber {
            get {
                return ResourceManager.GetString("personnelNumber", resourceCulture);
            }
        }
        
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        internal static string orderNumber {
            get {
                return ResourceManager.GetString("orderNumber", resourceCulture);
            }
        }
        
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        internal static string persons {
            get {
                return ResourceManager.GetString("persons", resourceCulture);
            }
        }
        
        internal static string articles {
            get {
                return ResourceManager.GetString("articles", resourceCulture);
            }
        }
        
        internal static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string createNewTQuestionWithName {
            get {
                return ResourceManager.GetString("createNewTQuestionWithName", resourceCulture);
            }
        }
        
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        internal static string articleType {
            get {
                return ResourceManager.GetString("articleType", resourceCulture);
            }
        }
        
        internal static string createNewTQuestion {
            get {
                return ResourceManager.GetString("createNewTQuestion", resourceCulture);
            }
        }
        
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        internal static string apprentices {
            get {
                return ResourceManager.GetString("apprentices", resourceCulture);
            }
        }
        
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        internal static string apprenticeships {
            get {
                return ResourceManager.GetString("apprenticeships", resourceCulture);
            }
        }
    }
}
