version: "3.7"
services:
  database:
    container_name: database
    image: mysql:latest
    expose: 
      - 3306
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./Database/data:/var/lib/mysql:rw
      - ./Database/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend
    restart: always

  backend:
    container_name: api
    expose:
      - 80
    ports:
      - 127.0.0.1:80:80
    networks:
      - backend
    build:
      context: ./PcmBackendApi
    restart: always
    
  frontend:
    container_name: webUi
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - backend
    build:
      context: ./PcmFrontendWebUi
    restart: always

networks:
  backend:
    name: backend-nw
    driver: bridge
